### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by KittenPixel-cell** [CedModV2/CedMod#37]
`
[2024-01-04 19:40:36.574 +00:00] [Error] [CedModV3] Failed to perform security challenge,
[2024-01-04 19:40:37.655 +00:00] [Info] [CedModV3] Performing security challenge

`

I get this issue.

**Comment by ced777ric** [comment]
there should be extra info in the error.
Have you run the setup command?

**Comment by KittenPixel-cell** [comment]
Yes.

**Comment by ced777ric** [comment]
I have restarted the challenge server, it should start working now.

**Comment by KittenPixel-cell** [comment]
![image](https://github.com/CedModV2/CedMod/assets/79544605/d243434c-9d6f-4ecd-8c29-1c52cb880285)
Looks like its starting working.

**Comment by KittenPixel-cell** [comment]
I will wait a bit

**Comment by ced777ric** [comment]
I have adjusted the configuration of the ChallengeServer it should be working now, i forgot to change the configuration from when servers moved.

**Comment by KittenPixel-cell** [comment]
Ok 
![image](https://github.com/CedModV2/CedMod/assets/79544605/98e88967-e7e3-4a9b-9d11-7bacddab73b3)
Works!
